# Generated by Django 4.2.26 on 2025-11-23 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asignado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'asignado',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'detalle_pedido',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField(blank=True, null=True)),
                ('forma_pago', models.CharField(blank=True, choices=[('Efectivo', 'Efectivo'), ('Tarjeta', 'Tarjeta'), ('Transferencia', 'Transferencia')], max_length=13, null=True)),
                ('estado', models.CharField(choices=[('PREPARACION', 'En Preparación'), ('LISTO', 'Listo para Retirar'), ('ENTREGADO', 'Entregado')], default='PREPARACION', max_length=20)),
            ],
            options={
                'db_table': 'pedidos',
                'managed': True,
            },
        ),
    ]
