# Generated by Django 4.2.26 on 2025-11-23 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('orders', '0001_initial'),
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='id_cliente',
            field=models.ForeignKey(blank=True, db_column='id_cliente', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.cliente'),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='id_sucursal',
            field=models.ForeignKey(blank=True, db_column='id_sucursal', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.sucursal'),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='id_trabajador',
            field=models.ForeignKey(blank=True, db_column='id_trabajador', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pedidos', to='users.trabajador'),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='id_pedido',
            field=models.ForeignKey(db_column='id_pedido', on_delete=django.db.models.deletion.CASCADE, to='orders.pedidos'),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='id_producto',
            field=models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, to='menu.producto'),
        ),
        migrations.AddField(
            model_name='asignado',
            name='id_pedido',
            field=models.ForeignKey(db_column='id_pedido', null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.pedidos'),
        ),
        migrations.AddField(
            model_name='asignado',
            name='id_producto',
            field=models.ForeignKey(db_column='id_producto', null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.producto'),
        ),
        migrations.AddField(
            model_name='asignado',
            name='id_trabajador',
            field=models.ForeignKey(db_column='id_trabajador', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.trabajador'),
        ),
    ]
